# Generated by Django 3.0.3 on 2020-02-16 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mysite.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Boroughs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='borough',
            name='Main_Img',
        ),
        migrations.AddField(
            model_name='borough',
            name='main_img',
            field=models.ImageField(null=True, upload_to='main_images/'),
        ),
        migrations.CreateModel(
            name='PrivateDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.FileField(storage=mysite.storage_backends.PrivateMediaStorage(), upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time this page was created. Automatically generated when the model saves.')),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('email', models.CharField(max_length=200)),
                ('content', models.TextField(default='Write the content of your page here.')),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('borough', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='Boroughs.Borough')),
            ],
        ),
    ]
