# Generated by Django 3.0.2 on 2020-02-02 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Boroughs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hotel',
            new_name='Boroughs',
        ),
        migrations.RenameField(
            model_name='boroughs',
            old_name='hotel_Main_Img',
            new_name='borough_Main_Img',
        ),
    ]
