# Generated by Django 3.0.2 on 2020-02-02 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Boroughs', '0002_auto_20200201_2038'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Boroughs',
            new_name='Borough',
        ),
    ]
