# Generated by Django 3.0.3 on 2020-02-24 05:27

from django.db import migrations, models
import mysite.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('Boroughs', '0002_auto_20200216_1538'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AddField(
            model_name='photo',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(storage=mysite.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
        migrations.DeleteModel(
            name='PrivateDocument',
        ),
    ]
