# Generated by Django 3.0.3 on 2020-02-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boroughs', '0003_auto_20200223_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
