# Generated by Django 3.0.2 on 2020-02-02 11:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Boroughs', '0003_auto_20200201_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borough',
            name='name',
        ),
        migrations.AddField(
            model_name='borough',
            name='content',
            field=models.TextField(default='Write the content of your page here.'),
        ),
        migrations.AddField(
            model_name='borough',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date and time this page was created. Automatically generated when the model saves.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borough',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='The date and time this page was updated. Automatically generated when the model updates.'),
        ),
        migrations.AddField(
            model_name='borough',
            name='slug',
            field=models.CharField(blank=True, editable=False, help_text="Unique URL path to access this borough's page. Generated by the system.", max_length=600),
        ),
        migrations.AddField(
            model_name='borough',
            name='title',
            field=models.CharField(default='Title of your page.', max_length=600, unique=True),
        ),
    ]
