# Generated by Django 3.0.3 on 2020-02-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boroughs', '0004_photo_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='borough',
            name='zipcode',
            field=models.IntegerField(default=9401, help_text='Add the zipcode of this borough'),
        ),
    ]
