# Generated by Django 3.0.3 on 2020-02-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boroughs', '0005_borough_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='borough',
            name='sources',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
