# Generated by Django 3.0.3 on 2020-02-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boroughs', '0006_auto_20200224_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borough',
            name='sources',
            field=models.URLField(blank=True, null=True),
        ),
    ]
